## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Hugo Story"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

#[Params]
#  description = "Gloriette Spirits & Botanicals"
#  logo = "images/banner.jpg"
#  favicon = true
#
#[Params.social]
#  email = "enquiries@gloriette.co.uk"
#  facebook = "https://facebook.com/GlorietteGin/"
#  twitter = "https://twitter.com/Gloriette_Gin"
#  instagram = "https://instagram.com/GlorietteGin"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]